name = "roblox-standard"
std = "roblox"

[rules]
unused_variable = "allow"
shadowing = "allow"
multiple_statements = "allow"
incorrect_standard_library_use = "warn"
global_usage = "warn"

[lints]
global_usage = "allow"
