--!strict
--==============================================================
-- MMMM Context: The collective repository of neglected semantics. When Feral Typos are ignored, they sink into the Underworld, eventually manifesting as a Server-Wide Cacophony.
--==============================================================
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Workspace = game:GetService("Workspace")
local Players = game:GetService("Players")

local Packages = ReplicatedStorage:WaitForChild("Packages")
local Knit = require(Packages:WaitForChild("Knit"))

-- Config
local TYPO_MERGE_THRESHOLD = 5 -- Lowered for easier triggering during tests
local DUNGEON_LOCATION = CFrame.new(0, -90, 0) -- Beneath the map, inside the dungeon walls generated by TerrainService

local LexicalUnderworldService = Knit.CreateService {
    Name = "LexicalUnderworldService",
    Client = {
        CacophonySummoned = Knit.CreateSignal(),
        CacophonyDefeated = Knit.CreateSignal(),
    },
}

-- State
local NeglectedTypos = {}
local IsRaidActive = false
local CacophonyModel: Model? = nil
local CurrentCacophonyHealth = 0
local MaxCacophonyHealth = 0

function LexicalUnderworldService:KnitStart()
    print("[LexicalUnderworldService] Tracking feral linguistic decay...")
    
    -- Listen to Feral Typo logic
    local FeralTypoService = Knit.GetService("FeralTypoService")
    if FeralTypoService then
        -- We want to track whenever a typo is spawned but not engaged.
        -- We will poll the workspace for any Typos that survive for too long.
        task.spawn(function()
            while true do
                task.wait(60) -- Check every 60 seconds
                self:AssimilateNeglectedTypos()
            end
        end)
    end
end

-- Checks for ancient typos wandering aimlessly
function LexicalUnderworldService:AssimilateNeglectedTypos()
    if IsRaidActive then return end
    
    local feralCount = 0
    -- Iterate over spawned Typos in Workspace
    for _, child in ipairs(Workspace:GetChildren()) do
        if child:GetAttribute("IsFeralTypo") then
            local spawnTime = child:GetAttribute("SpawnTime") or os.time()
            if os.time() - spawnTime > 120 then -- If older than 2 mins
                -- It decays and merges into the underworld
                table.insert(NeglectedTypos, child:GetAttribute("FailedWord"))
                child:Destroy()
                feralCount += 1
            end
        end
    end
    
    if feralCount > 0 then
        print(string.format("[LexicalUnderworldService] Assimilated %d neglected typos.", feralCount))
    end
    
    if #NeglectedTypos >= TYPO_MERGE_THRESHOLD then
        self:SummonCacophony()
    end
end

function LexicalUnderworldService:SummonCacophony()
    if IsRaidActive then return end
    IsRaidActive = true
    
    print("[LexicalUnderworldService] ⚠️ The combined weight of ignored errors has ruptured reality. The Cacophony stirs!")
    
    -- Use up the raw materials
    local syllables = table.concat(NeglectedTypos, " \n")
    MaxCacophonyHealth = #NeglectedTypos * 100
    CurrentCacophonyHealth = MaxCacophonyHealth
    NeglectedTypos = {} -- Wipe memory

    -- Trigger the Zeitgeist paradigm shift forcefully
    local ZeitgeistService = Knit.GetService("ZeitgeistService")
    if ZeitgeistService then
        -- Force a "Shadow" or "Chaos" override regardless of tally
        ZeitgeistService:TriggerAnomaly("Shadow", "CACOPHONY AWAKENED")
    end

    -- Tell all clients to show UI/play ominous music
    self.Client.CacophonySummoned:FireAll(MaxCacophonyHealth)
    
    -- Teleport eligible players down to the dungeon (or create a portal in Town Square)
    self:SpawnDungeonPortal()
    
    -- Physically Build the Boss
    CacophonyModel = Instance.new("Model")
    CacophonyModel.Name = "The Cacophony"
    
    local core = Instance.new("Part")
    core.Name = "Core"
    core.Shape = Enum.PartType.Ball
    core.Size = Vector3.new(30, 30, 30)
    core.Material = Enum.Material.Neon
    core.Color = Color3.fromRGB(0, 0, 0)
    core.Anchored = true
    core.CFrame = DUNGEON_LOCATION + Vector3.new(0, 15, 0)
    core.Parent = CacophonyModel
    CacophonyModel.PrimaryPart = core
    
    local pLight = Instance.new("PointLight")
    pLight.Color = Color3.fromRGB(150, 0, 255)
    pLight.Range = 100
    pLight.Brightness = 5
    pLight.Parent = core
    
    local aura = Instance.new("ParticleEmitter")
    aura.Texture = "rbxassetid://7335198031"
    aura.Color = ColorSequence.new(Color3.fromRGB(85, 0, 127))
    aura.Size = NumberSequence.new(10, 20)
    aura.Rate = 50
    aura.Speed = NumberRange.new(5, 10)
    aura.Lifetime = NumberRange.new(3, 5)
    aura.EmissionDirection = Enum.NormalId.Out
    aura.Parent = core
    
    local sGui = Instance.new("SurfaceGui")
    sGui.Face = Enum.NormalId.Front
    sGui.CanvasSize = Vector2.new(800, 800)
    sGui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
    sGui.PixelsPerStud = 50
    sGui.Parent = core
    
    local errorText = Instance.new("TextLabel")
    errorText.Size = UDim2.new(1, 0, 1, 0)
    errorText.BackgroundTransparency = 1
    errorText.Text = syllables
    errorText.TextColor3 = Color3.fromRGB(255, 0, 0)
    errorText.TextScaled = true
    errorText.TextWrapped = true
    errorText.Font = Enum.Font.Code
    errorText.Parent = sGui

    -- Set Boss Health Bar Data
    CacophonyModel:SetAttribute("Health", CurrentCacophonyHealth)
    CacophonyModel:SetAttribute("MaxHealth", MaxCacophonyHealth)

    CacophonyModel.Parent = Workspace
    
    -- Server Loop for Boss fight
    task.spawn(function()
        local TimeAlive = 0
        while IsRaidActive and CacophonyModel and CacophonyModel.Parent do
            task.wait(1)
            TimeAlive += 1
            
            -- If boss survives for 5 minutes (300 seconds), it escapes and drains everyone's Semantic Points
            if TimeAlive > 300 then
                self:RaidFailed()
                break
            end
            
            -- Ambient boss attacks (Flinging typos at players)
            if TimeAlive % 10 == 0 then
                self:CastBossAttack()
            end
        end
    end)
end

function LexicalUnderworldService:SpawnDungeonPortal()
    local portal = Instance.new("Part")
    portal.Name = "UnderworldPortal"
    portal.Shape = Enum.PartType.Cylinder
    portal.Size = Vector3.new(2, 10, 10)
    portal.Color = Color3.fromRGB(85, 0, 127)
    portal.Material = Enum.Material.Neon
    portal.Anchored = true
    portal.CanCollide = false
    portal.CFrame = CFrame.new(0, 10, 50) -- Town Square Offset
    portal.Orientation = Vector3.new(0, 0, 90)
    
    local prompt = Instance.new("ProximityPrompt")
    prompt.ActionText = "Fall into the Abyss"
    prompt.ObjectText = "Lexical Underworld"
    prompt.HoldDuration = 1
    prompt.Parent = portal
    
    prompt.Triggered:Connect(function(player)
        if player.Character and player.Character.PrimaryPart then
            -- Teleport straight to the Dungeon arena
            player.Character:SetPrimaryPartCFrame(DUNGEON_LOCATION + Vector3.new(50, 5, 50))
        end
    end)
    
    portal.Parent = Workspace
    
    -- Clean up portal when raid ends
    task.spawn(function()
        while IsRaidActive do task.wait() end
        portal:Destroy()
    end)
end

function LexicalUnderworldService:CastBossAttack()
    if not CacophonyModel or not CacophonyModel.PrimaryPart then return end
    
    print("[LexicalUnderworldService] The Cacophony lashes out with fragmented sentences!")
    -- Send projectiles at all players currently in the dungeon radius (Y < -30)
    for _, player in ipairs(Players:GetPlayers()) do
        if player.Character and player.Character.PrimaryPart then
            local hrp = player.Character.PrimaryPart
            if hrp.Position.Y < -30 then
                -- Apply pedagogical friction - scramble inventory or slow speed
                local hum = player.Character:FindFirstChild("Humanoid")
                if hum then
                    hum.WalkSpeed = 8 -- Slow them down due to linguistic confusion
                    task.delay(5, function() if hum then hum.WalkSpeed = 16 end end)
                end
            end
        end
    end
end

-- Receives pedagogical submissions from the client
function LexicalUnderworldService.Client:SubmitCorrection(player: Player, wordString: string)
    return self.Server:ProcessCorrectionWord(player, wordString)
end

-- Called by the Combat System or Slime Signature Move integration
-- We'll allow the server to securely record corrections dealt by slimes to the boss
function LexicalUnderworldService:ProcessCorrectionWord(player: Player, word: string): (boolean, string)
    if not IsRaidActive or not CacophonyModel then return false, "No Raid Active" end
    
    word = word:lower()
    
    -- Verify the word is real (simple length check or dictionary check if implemented)
    local WordDatabase = require(ReplicatedStorage.Shared.WordDatabase)
    if not WordDatabase[word] and #word < 3 then
        return false, "Invalid word."
    end
    
    -- Pedagogical scaling: Base 10 + 2 per letter + Rarity bonus
    local correctionPower = 10 + (#word * 2)
    
    if WordDatabase[word] and WordDatabase[word].GradeLevel then
        local gradeMults = { ["K-2"] = 1, ["3-5"] = 1.5, ["6-9"] = 2, ["10-12"] = 3, ["Graduate"] = 5 }
        correctionPower = correctionPower * (gradeMults[WordDatabase[word].GradeLevel] or 1)
    end
    
    CurrentCacophonyHealth -= math.floor(correctionPower)
    CacophonyModel:SetAttribute("Health", math.max(0, CurrentCacophonyHealth))
    
    print(string.format("[LexicalUnderworldService] %s applied %d grammatical correction to the Cacophony with the word '%s'!", player.Name, correctionPower, word))
    
    -- Update Boss UI scale to shrink it
    local scaleFactor = math.max(0.3, CurrentCacophonyHealth / MaxCacophonyHealth)
    local tweenInfo = TweenInfo.new(0.5, Enum.EasingStyle.Elastic)
    local TweenService = game:GetService("TweenService")
    
    TweenService:Create(CacophonyModel.PrimaryPart, tweenInfo, {
        Size = Vector3.new(30 * scaleFactor, 30 * scaleFactor, 30 * scaleFactor)
    }):Play()
    
    if CurrentCacophonyHealth <= 0 then
        self:RaidVictory(player) -- Player who got the final hit gets credit
    end
    
    return true, "Hit!"
end

function LexicalUnderworldService:RaidVictory(finalHitPlayer: Player)
    IsRaidActive = false
    print("[LexicalUnderworldService] The server triumphed! The Cacophony has been purified.")
    
    if CacophonyModel then
        -- Explosion particle effect here before destroy
        CacophonyModel:Destroy()
    end
    
    self.Client.CacophonyDefeated:FireAll()
    
    -- Massive rewards for all players in the dungeon
    local DataService = Knit.GetService("DataService")
    if DataService then
        for _, player in ipairs(Players:GetPlayers()) do
            if player.Character and player.Character.PrimaryPart and player.Character.PrimaryPart.Position.Y < -30 then
                -- Grant massive XP / Unique item drops
                local profile = DataService:GetProfile(player)
                if profile then
                    profile.Inventory.Words = profile.Inventory.Words or {}
                    table.insert(profile.Inventory.Words, "Triumph")
                    DataService.Client.DataUpdated:Fire(player, "Inventory", profile.Inventory)
                    
                    if player == finalHitPlayer then
                        DataService:UnlockAchievement(player, "slayer_of_cacophony")
                    end
                end
            end
        end
    end
    
    -- Reset Zeitgeist
    local ZeitgeistService = Knit.GetService("ZeitgeistService")
    if ZeitgeistService then
        ZeitgeistService:RecordSemanticEvent("Purification", "Light", "triumph")
        ZeitgeistService:ClearAnomaly()
    end
end

function LexicalUnderworldService:RaidFailed()
    IsRaidActive = false
    print("[LexicalUnderworldService] 💀 The Raid Failed. The Cacophony scattered its corruption.")
    
    if CacophonyModel then CacophonyModel:Destroy() end
    self.Client.CacophonyDefeated:FireAll() -- We use same event but maybe flag it as failed
    
    local ZeitgeistService = Knit.GetService("ZeitgeistService")
    if ZeitgeistService then
        ZeitgeistService:ClearAnomaly() -- Reverts back to normal but the penalties are felt
    end
end

return LexicalUnderworldService
